name: lint workflows

on:
  pull_request:
    branches: [main]
  push:
    branches-ignore: [main]

permissions:
  contents: read
  packages: read
  statuses: write

jobs:
  lint-workflows:
    uses: senzing-factory/build-resources/.github/workflows/lint-workflows.yaml@v1
